"use strict";
//Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("../src/index");
var cnsl = new index_1.Cnsl();
var arr1 = 'a,b,c'.split(",");
var obj = cnsl.ao(arr1);
console.log("'".concat(obj.a, "'"));
cnsl.cursor(10, 10);
var log = cnsl.log;
log(cnsl.msg("example", ['test', 'cnsl'], '-G_R Y W'));